akula-bft/akula

src/downloader/downloader_impl.rs, src/downloader/message_decoder.rs, src/downloader/messages.rs, src/downloader/sentry_client_impl.rs
Parse incoming NewBlockHashes messages.
Note: `From<Message> for EthMessageId` was changed to a plain function message_eth_id to work with a Message reference, because the Message value is no longer Copy-able since it potentially contains a Vec.
=> Parse NewBlockHashes

src/downloader/block_id.rs, src/downloader/message_decoder.rs, src/downloader/messages.rs
* BlockHeaders
* NewBlock
* NewPooledTransactionHashes
Note: `Box<BlockType>` is to avoid 
warning: large size difference between variants (this variant is 696 bytes)
=> Parse common incoming messages

Cargo.toml, src/downloader/downloader_impl.rs, src/downloader/downloader_tests.rs, src/downloader/message_decoder.rs, src/downloader/messages.rs, src/downloader/mod.rs, src/downloader/sentry_client.rs, src/downloader/sentry_client_impl.rs, src/downloader/sentry_client_mock.rs, src/downloader/sentry_client_reactor.rs
Ability to send and receive messages simultaneously across threads.
send_message and receive_messages are synchronous and don't require a mutable borrowing.
The processing happens inside an event loop task.
=> SentryClientReactor

Cargo.toml, src/changeset/storage.rs, src/downloader/downloader_impl.rs, src/downloader/headers/fetch_receive_stage.rs, src/downloader/headers/fetch_request_stage.rs, src/downloader/headers/header_slices.rs, src/downloader/headers/mod.rs, src/downloader/headers/refill_stage.rs, src/downloader/headers/retry_stage.rs, src/downloader/headers/save_stage.rs, src/downloader/headers/ui_crossterm.rs, src/downloader/headers/ui_tracing.rs, src/downloader/headers/verify_stage.rs, src/downloader/mod.rs, src/downloader/sentry_client_reactor.rs, src/downloader/ui_system.rs, src/downloader/ui_view.rs, src/lib.rs
The preverified headers are downloaded with a help of a HeaderSlices data structure.
HeaderSlices is a memory-limited buffer of HeaderSlice objects, each containing a sequential slice of headers.
Example of a HeaderSlices with max_slices = 3:
* HeaderSlice 0: headers 0-192
* HeaderSlice 1: headers 192-384
* HeaderSlice 2: headers 384-576
Each HeaderSlice has a status:
// intialized, needs to be obtained
Empty,
// fetch request sent to sentry
Waiting,
// received from sentry
Downloaded,
// block hashes are matching the expected ones
Verified,
// saved in the database
Saved,
Downloading happens with several stages where each of the stages processes blocks in one status, and updates them to proceed to the next status. All stages runs in parallel, although most of the time only one of the …
=> HeaderSlices: preverified headers downloader

src/downloader/headers/fetch_request_stage.rs, src/downloader/headers/header_slices.rs, src/downloader/headers/retry_stage.rs
If a headers slice fetch request was sent, it gets Waiting status.
When it is Waiting for too long, it can timeout.
Apply the retry logic for each slice individually if it times out.
The timeout has a back off logic: it increases if there's no reply with each retry attempt.
=> RetryStage: retry requests only if needed.

src/downloader/downloader_impl.rs, src/downloader/headers/header_slices.rs, src/downloader/headers/ui_crossterm.rs, src/downloader/headers/verify_stage.rs
Preverified headers downloader process stops when it loads
all header slices until the max known preverified hash.
Since preverified hashes act as slices boundaries,
the number of slices to download is 1 less than the number of hashes.
=> RefillStage: stop refilling when everything is loaded

.gitignore, bin/akula-ddl.rs, src/downloader/downloader_impl.rs, src/downloader/downloader_tests.rs, src/downloader/headers/fetch_receive_stage.rs, src/downloader/headers/header_slices.rs, src/downloader/headers/save_stage.rs, src/downloader/opts.rs, src/kv/mod.rs
SaveStage is by saving the verified headers
into the "Header" table in the key-value database.
It uses the header hashes as keys and RLP data as values.
HeaderSlices is refactored so that find_by_status
is not holding the overall lock.
It returns a detached RC reference to a single HeaderSlice.
This allows to hold the HeaderSlice lock while blocking on await in save_pending,
and let other stages proceed at the same time.
=> Header downloader: SaveStage.

.gitignore, src/downloader/downloader_impl.rs, src/downloader/headers/fetch_receive_stage.rs, src/downloader/sentry_client.rs, src/downloader/sentry_client_reactor.rs, src/downloader/ui_system.rs
* refactor SentryClientReactorEventLoop to be able to send and receive simultaneously
previously if sentry.send_message was blocked on await, the loop was making no progress
even if the incoming messages were in in_stream.next.
Now send and receive streams are processed in parallel.
* avoid premature SentryClientReactorEventLoop exit causing fetch_request_stage_stream failure: Err(ReactorStopped)
* avoid retrying queued sent messages by having only 1 message in the channel at a time.
if it is > 1 there's a chance that it is not sent to congested upstream within 5 sec,
and after retry we have 2 identical requests in the queue. When they get executed
we are getting a "slice that we didn't request".
=> Header downloader: queue optimizations.

.gitignore, src/downloader/downloader_impl.rs, src/downloader/mod.rs, src/downloader/sentry_client.rs, src/downloader/sentry_client_connector.rs, src/downloader/sentry_client_impl.rs, src/downloader/sentry_client_mock.rs, src/downloader/sentry_client_reactor.rs
**sentry_client_connector** module implements the basic reconnection logic: connecting to sentry GRPC and retrying every 5 sec on failure. This logic is reused for the initial connection (before status is sent), and also for disconnects happening during downloading.
**connector_stream** is a stream that produces the initial connected sentry client, and then new clients after each reconnect. polling this stream for the first time returns the connected client. polling it for the second, third etc. time forces a new connection (after some retries) and a new client.
When a disconnect is detected (during send or receive), we have to reconnect and recreate the send/receive streams providing a new sentry client. During that time the send/receive handling is paused (by removing the streams from …
=> Reconnect to sentry.

src/downloader/headers/fetch_request_stage.rs, src/downloader/headers/header_slice_status_watch.rs, src/downloader/headers/mod.rs, src/downloader/headers/refill_stage.rs, src/downloader/headers/retry_stage.rs, src/downloader/headers/save_stage.rs, src/downloader/headers/verify_stage.rs
The "wait for slices in status X" logic was duplicated across stages.
This PR refactors it into a HeaderSliceStatusWatch helper.
=> Downloader: refactor status watches in stages.

src/downloader/downloader_impl.rs, src/downloader/headers/downloader.rs, src/downloader/headers/downloader_linear.rs, src/downloader/headers/downloader_preverified.rs, src/downloader/headers/mod.rs, src/downloader/headers/stage_stream.rs
The header downloading will have 3 phases.
This refactoring separates the first phase - preverified.
The second phase - linear phase is a disabled copy-paste of preverified for now.
=> Downloader: separate linear phase.

Cargo.toml, src/downloader/headers/save_stage.rs
The header downloader SaveStage is adapted to not rely on this feature.
This feature allows locking the RwLock across threads,
but in async runtime it can cause deadlocks,
because hard-locking a thread disables it for the async scheduling.
=> Rollback parking_lot send_guard feature.

src/downloader/headers/header_slice_status_watch.rs, src/downloader/headers/header_slices.rs, src/downloader/headers/save_stage.rs
Saving headers in the increasing block number order
might give performance benefits.
=> Downloader: monotonic saving.

src/downloader/headers/downloader_linear.rs, src/downloader/headers/verify_stage_linear.rs, src/downloader/headers/verify_stage_preverified.rs
If the fetched slice is empty or has a size that doesn't match to requested,
we need to fail the verification in order to try to download it again.
=> Downloader: verify slice sizes.

src/downloader/downloader_impl.rs, src/downloader/headers/downloader.rs, src/downloader/headers/downloader_linear.rs, src/downloader/headers/downloader_preverified.rs, src/downloader/headers/fetch_receive_stage.rs, src/downloader/headers/fetch_request_stage.rs, src/downloader/headers/header_slices.rs, src/downloader/headers/mod.rs, src/downloader/headers/penalize_stage.rs, src/downloader/headers/ui_crossterm.rs, src/downloader/headers/verify_stage_linear.rs, src/downloader/headers/verify_stage_linear_link.rs, src/downloader/headers/verify_stage_preverified.rs, src/sentry/sentry_client.rs, src/sentry/sentry_client_impl.rs, src/sentry/sentry_client_mock.rs, src/sentry/sentry_client_reactor.rs
If a slice verification has failed, we call penalize_peer() on sentry,
which disconnects the peer that has given us this slice.
If the node is full, it will be hard for that peer to reconnect again.
The slice is setup for a retry, and hopefully will be fetched from another peer.
* refactor to use tokio's RwLock on sentry reactor
in order to be able to call async reactor methods from stages
(await while holding the read() lock)
=> Downloader: penalize a peer if we fail to verify.

src/downloader/downloader_impl.rs, src/downloader/headers/downloader.rs, src/downloader/headers/downloader_linear.rs, src/downloader/headers/header_slice_verifier.rs, src/downloader/headers/preverified_hashes_config.rs, src/downloader/headers/verify_stage_linear.rs, src/downloader/headers/verify_stage_linear_link.rs, src/sentry/chain_config.rs
During the linear header download phase we need to verify that the header difficulty field is correct
with respect to its parent header (and the current chain config rules).
VerifyStageLinear stage checks that this relation holds between each sequential pair of a headers slice.
VerifyStageLinearLink stage checks this relation on the slice edges - between the last header of a previous verified slice (last verified header) and the first header of an internally verified slice.
=> Downloader: verify_slice_difficulties.

src/downloader/headers/downloader.rs, src/sentry/sentry_client_reactor.rs
Downloader has 2 sequential phases: preverified and linear.
Enabling them both was breaking the downloader test, because in the preverified downloader phase
sending a request closes the SentryClientMock receiver, this causes a reactor loop stream end
and clear the receive_messages_senders to unblock the FetchReceiveStage (and exit the downloader loop).
But then in the linear phase receive_messages() produced an error
"SentryClientReactor unexpected filter_id".
To fix this this condition is checked in receive_messages() and an empty stream is returned,
so that the next FetchReceiveStage immediately ends, and the linear phase loop exits cleanly too.
=> Downloader: enable 2nd phase and fix the test.

src/downloader/downloader_impl.rs, src/sentry/chain_config.rs, src/sentry/sentry_client.rs, src/sentry/sentry_client_connector.rs
If a sentry process dies and restarts, it forgets the status info.
When reconnected, we need to call set_status again.
=> Downloader: set_status after reconnecting.

src/downloader/headers/downloader_linear.rs, src/downloader/headers/downloader_preverified.rs, src/downloader/ui_system.rs
Otherwise it was possible that previous phase keeps printing progress when the next is already started.
=> Downloader: remove view on phase exit.

bin/akula-toolbox.rs, src/downloader/downloader_impl.rs, src/downloader/downloader_tests.rs, src/downloader/mod.rs, src/downloader/sentry_status_provider.rs, src/sentry/chain_config.rs, src/sentry/sentry_client_connector.rs, src/sentry/sentry_client_reactor.rs, src/stages/downloader.rs
The sentry reactor is managed outside of the staged sync loop,
so that it stays connected all the time,
and it's possible to use the sentry API in any other stages.
=> Downloader refactoring: lift sentry reactor out of the downloader.

bin/akula-toolbox.rs, src/downloader/downloader_impl.rs, src/downloader/downloader_tests.rs, src/downloader/headers/downloader.rs, src/downloader/headers/downloader_linear.rs, src/downloader/headers/downloader_preverified.rs, src/downloader/headers/header_slices.rs, src/downloader/opts.rs, src/downloader/ui_system.rs, src/stages/downloader.rs
To give room to the other stages for processing.
akula-toolbox download-headers --downloader.headers-batch-size 1920
=> Downloader: exit stage every N blocks.

bin/akula-toolbox.rs, src/downloader/downloader_impl.rs, src/downloader/downloader_tests.rs, src/downloader/headers/downloader.rs, src/downloader/opts.rs, src/stages/downloader.rs
Pass the size of header slices from command line:
--downloader.headers-mem-limit 50
=> Downloader: mem limit CLI option.

src/downloader/headers/fetch_request_stage.rs, src/downloader/headers/header_slices.rs, src/downloader/headers/penalize_stage.rs, src/downloader/headers/retry_stage.rs, src/downloader/headers/save_stage.rs, src/downloader/headers/verify_stage_linear.rs, src/downloader/headers/verify_stage_linear_link.rs, src/downloader/headers/verify_stage_preverified.rs
The logic was based on indexes, but they are not stable
since save_slice() is async, RefillStage might or might not trigger
in between and remove the saved slices.
Also it was possible to not have RefillStage call between SaveStage calls.
In this case we've got Saved status at front, and confused it with a non-monotonic case.
Fixed by searching for the next slice in each loop iteration,
skipping already processed ones.
=> Downloader: fix save_pending_monotonic logic.

bin/akula-toolbox.rs, bin/akula.rs, src/downloader/downloader_impl.rs, src/downloader/downloader_tests.rs, src/downloader/headers/downloader.rs, src/downloader/headers/downloader_linear.rs, src/downloader/headers/downloader_preverified.rs, src/downloader/headers/preverified_hashes_config.rs, src/downloader/ui_system.rs, src/stages/downloader.rs
This is a low-hanging fruit optimization.
PreverifiedHashesConfig was read multiple times (each time the stage was run),
and it accounted for 3% of time.
=> Downloader: load preverified hashes config once.

Cargo.lock, Cargo.toml, src/downloader/headers/header_slices.rs, src/downloader/headers/mod.rs, src/downloader/headers/parallel.rs, src/downloader/headers/verify_stage_linear.rs, src/downloader/headers/verify_stage_preverified.rs
verify_pending locks the header_slices for too long inside for_each.
Unlock it more often for each batch of slices,
and process this batch in parallel.
This saves 15% of the overall time.
=> Downloader: fix verify_pending congestion.

Cargo.lock, Cargo.toml, src/downloader/headers/header_slices.rs, src/downloader/headers/mod.rs, src/downloader/headers/parallel.rs, src/downloader/headers/verify_stage_linear.rs, src/downloader/headers/verify_stage_preverified.rs, src/lib.rs
LinkedList was needed to delete slices from the middle.
Since now saving is monotonic, we only delete from the beginning,
and we refill at the end, therefore a deque is more adequate.
=> Downloader: switch HeaderSlices to deque.

src/downloader/headers/fetch_receive_stage.rs, src/downloader/headers/header.rs, src/downloader/headers/header_slice_verifier.rs, src/downloader/headers/header_slices.rs, src/downloader/headers/mod.rs, src/downloader/headers/save_stage.rs, src/downloader/headers/verify_stage_linear_link.rs
Use a BlockHeader wrapper instead of models directly.
=> Downloader: refactor header.

src/downloader/headers/header.rs, src/downloader/headers/verify_stage_linear.rs, src/downloader/headers/verify_stage_preverified.rs
This caches the hash() to avoid the 2nd recomputation in SaveStage.
Previously it was computed twice:
* In VerifyStage to connect hash(parent) to child.parent_hash;
* In SaveStage to obtain a HeaderKey for saving.
With this caching it saves about 17% of header downloader running time:
This bumps the max speed from about 4-5K blocks/sec to about 5-6K blocks/sec,
which translates to about 10-15 minutes saving on mainnet.
=> Downloader: cache hash() v2 (inside downloader).

src/downloader/headers/header.rs, src/downloader/headers/save_stage.rs
This reuses precomputed RLP bytes in SaveStage.
Previously it was computed twice:
* In VerifyStage to as a part of computing hash();
* In SaveStage as a part of Table::Value::encode() serialization for saving;
Reusing the RLP bytes saves about 10% of header downloader running time.
=> Downloader: save precomputed header RLP.

bin/akula-toolbox.rs, bin/akula.rs
Make sure that the data_dir exists before trying to
create/open a writable database inside data_dir/chaindata.
=> Akula: fix panic without data dir in toolbox.

src/downloader/headers/verify_stage_linear_link.rs
If a slice is verified and saved too fast,
the next slice monotonic verification aborts.
We can't abort on Saved slices, because they will be evicted,
and so the remaining_count won't change (potentially),
causing the VerifyStageLinearLink to wait forever.
It is fine to abort on Invalid, because they are gonna be redownloaded,
verified internally, and the remaining_count will change.
=> Downloader: fix linear phase hang if saved to fast.

src/downloader/headers/downloader_forky.rs, src/downloader/headers/downloader_linear.rs, src/downloader/headers/fetch_receive_stage.rs, src/downloader/headers/verify_stage_linear.rs, src/downloader/headers/verify_stage_linear_link.rs
In the forky phase we might get partial slices,
but we still want to fetching and internal verification to succeed.
=> Downloader: postpone slice size check.

src/downloader/downloader_tests.rs, src/downloader/headers/downloader.rs, src/downloader/headers/downloader_forky.rs, src/downloader/headers/fork_mode_stage.rs, src/downloader/headers/header_slices.rs, src/downloader/headers/mod.rs, src/downloader/headers/ui_crossterm.rs, src/downloader/headers/verify_stage_forky_link.rs
Fork mode starts when a slice fails to link to the canonical chain
in the forky phase for the first time (in VerifyStageLinearLink).
Right when it starts, the fork and canonical chain continuation blocks
are updated for Refetch (ForkModeStage::setup).
The fork mode start test verifies that given this condition,
the VerifiedInternally slice that fails to link (denoted as "|=")
gets marked with a Fork status (denoted as "Y"),
and that it is backed up to fork_status and becomes emtpy
(denoted as "-/Y") for the canonical chain continuation.
In addition, the canonical chain last Saved slice (denoted as "+")
is backed up to fork_status and becomes emtpy (denoted as "-/+")
for the fork chain continuation.
=> Downloader: fork mode start test.

src/downloader/downloader_impl.rs, src/downloader/downloader_tests.rs, src/downloader/headers/downloader.rs, src/downloader/headers/downloader_forky.rs, src/downloader/headers/downloader_linear.rs, src/downloader/headers/downloader_preverified.rs, src/downloader/headers/downloader_stage_loop.rs, src/downloader/headers/fetch_request_stage.rs, src/downloader/headers/fork_mode_stage.rs, src/downloader/headers/header_slice_status_watch.rs, src/downloader/headers/header_slice_verifier.rs, src/downloader/headers/header_slice_verifier_mock.rs, src/downloader/headers/header_slices.rs, src/downloader/headers/mod.rs, src/downloader/headers/refetch_stage.rs, src/downloader/headers/refill_stage.rs, src/downloader/headers/retry_stage.rs, src/downloader/headers/verify_stage_forky_link.rs, src/downloader/headers/verify_stage_linear.rs, src/downloader/headers/verify_stage_linear_link.rs, src/downloader/mod.rs, src/downloader/ui_system.rs, src/stages/downloader.rs
Mode::Linear of VerifyStageForkyLink continues for as long as
it is possible to link slices to the canonical chain.
The test verifies that given a VerifiedInternally slice ("=")
it transitions to Saved ("+").
This has to be different from a slice with a broken link ("|="),
which must start Mode::Fork (in the fork_mode_start() test).
To distinguish the situations a HeaderSliceVerifierMock is used.
HeaderSliceVerifier is changed to a trait in stages
in order to substitute the verification logic for tests.
=> Downloader: basic verify link test.

src/downloader/headers_downloader/downloader.rs, src/downloader/headers_downloader/downloader_forky.rs, src/downloader/headers_downloader/downloader_linear.rs, src/downloader/headers_downloader/downloader_preverified.rs, src/downloader/headers_downloader/downloader_stage_loop.rs, src/downloader/headers_downloader/downloader_tests.rs, src/downloader/headers_downloader/headers/header_slices.rs, src/downloader/headers_downloader/stages/fetch_receive_stage.rs, src/downloader/headers_downloader/stages/fetch_request_stage.rs, src/downloader/headers_downloader/stages/fork_mode_stage.rs, src/downloader/headers_downloader/stages/penalize_stage.rs, src/downloader/headers_downloader/stages/refetch_stage.rs, src/downloader/headers_downloader/stages/refill_stage.rs, src/downloader/headers_downloader/stages/retry_stage.rs, src/downloader/headers_downloader/stages/save_stage.rs, src/downloader/headers_downloader/stages/stage.rs, src/downloader/headers_downloader/stages/top_block_estimate_stage.rs, src/downloader/headers_downloader/stages/verify_stage_forky_link.rs, src/downloader/headers_downloader/stages/verify_stage_linear.rs, src/downloader/headers_downloader/stages/verify_stage_linear_link.rs, src/downloader/headers_downloader/stages/verify_stage_preverified.rs, src/downloader/headers_downloader/verification/header_slice_verifier.rs, src/downloader/headers_downloader/verification/header_slice_verifier_mock.rs, src/downloader/headers_downloader/verification/preverified_hashes_config.rs, src/sentry/sentry_client_mock.rs
Tests to verify that in fork mode:
* extending the fork chain down is possible
* extending the canonical chain up is possible
Changes:
* preverified_hashes_config can be empty (for tests) to effectively skip DownloaderPreverified phase
* can_proceed_check is generalized for tests: the test is run for as long as any stage can make progress
when SentryClientMock is drained, FetchReceiveStage is gonna stop making progress,
but other stages still can, so that Downloaded status can proceed to Verified/Saved.
Without this change the test was ended prematurely.
* implemented parse_sentry description and related SentryClientMock logic:
when a request comes in for a known block - return that block, and remove from the list
when the known blocks list is empty - end the stream
* HeaderGenerator: …
=> Downloader: fork mode chain continuation tests.

src/downloader/headers_downloader/downloader.rs, src/downloader/headers_downloader/downloader_forky.rs, src/downloader/headers_downloader/downloader_linear.rs, src/downloader/headers_downloader/downloader_preverified.rs, src/downloader/headers_downloader/downloader_stage_loop.rs, src/downloader/headers_downloader/downloader_tests.rs, src/downloader/headers_downloader/headers/header_slice_status_watch.rs, src/downloader/headers_downloader/headers/header_slices.rs, src/downloader/headers_downloader/stages/fork_mode_stage.rs, src/downloader/headers_downloader/stages/mod.rs, src/downloader/headers_downloader/stages/save_stage.rs, src/downloader/headers_downloader/stages/verify_stage_forky_link.rs
Create a separate fork_header_slices for managing the fork.
The fork_header_slices progress is driven by a second group of stages.
The link verification stage is common and handles linking of both
main header_slices and fork_header_slices.
* discard_fork simplified
* switch_to_fork simplified
* verify_slices_link simplified
Improved:
* possible to start VerifyStageForkyLink in fork mode
* remaining_count update made safe from race conditions
* optimized range_difficulty
* handle possible case of continuation_slice = None
* fork_header_slices save stage saves the fork headers for reuse (fast setup and switching)
* this unblocks monotonic canonical chain save in fork mode
=> Downloader: refactoring to separate fork header_slices.

src/downloader/headers_downloader/downloader_tests.rs, src/downloader/headers_downloader/verification/header_slice_verifier_mock.rs, src/sentry/sentry_client_mock.rs
Generate fixed IDs instead of sequential IDs for the test headers.
By default the IDs match the block numbers.
Custom IDs are denoted as 'a, 'b, 'c etc.
For each slice headers a range of IDs is assigned:
'a = [0..192], 'b = [192..384], 'c = [384..576] etc.
HeaderSliceVerifierMock logic is simplified:
verify_link succeeds if the blocks have sequential IDs.
For example, 'c can be linked to 'd, but not to 'f,
while 'e can be linked to 'f.
This obsoletes the "|=" notation,
adds more checks for block positions in result/forked
and prepares for more complicated test cases.
=> Downloader: tests check IDs.

src/downloader/headers_downloader/downloader_tests.rs, src/downloader/headers_downloader/stages/fork_mode_stage.rs
New notation for fork connection points: `x
For example, slices = ". .`c" means that at position 'b we have a downloaded slice
that starts normally as 'b, but ends as if it was 'c.
Such slice can be connected to 'a on the left, and 'd on the right.
Note: the start ID is assumed based on the position ('a, 'b etc), only the alternative end ID is specified.
Technically this modifies the IDs of the last portion of the slice (currently just the last header).
For example, if 'c normally means IDs range [384..576],
`c at position 'b ('b = [192..384]) means that the slice gets IDs in range [192..576]
In practice: 192, 193, ... 382, 575
(i.e. the last 'b header ID 383 is replaced with the last 'c header ID 575)
In this case header 382 is a fork connection point.
=> Downloader: test fork connection.

src/downloader/headers_downloader/downloader_forky.rs, src/downloader/headers_downloader/downloader_tests.rs, src/downloader/headers_downloader/headers/header.rs, src/downloader/headers_downloader/headers/header_slices.rs
On restart, entering the forky phase,
reload saved headers from db into HeaderSlices.
This improves recover time after restart
to avoid re-downloading things that we alraedy have.
=> Downloader: reload saved headers on restart.

src/downloader/headers_downloader/downloader_forky.rs, src/downloader/headers_downloader/headers_ui/ui_crossterm.rs, src/downloader/headers_downloader/headers_ui/ui_tracing.rs
min_block_num rarely updates in the forky phase,
but the number of saved blocks goes up.
Fix DownloaderForkyReport.
Fix UI update.
=> Downloader: fix progress reporting in forky phase.

src/downloader/headers_downloader/downloader.rs, src/downloader/headers_downloader/downloader_forky.rs, src/downloader/headers_downloader/downloader_linear.rs
Forky needs to download 90K headers from the tip.
If forky downloads 50% of that, next run iteration will have start_block_num
just 45K headers away from the tip.
That breaks the idea of a constant window size.
Let's start the window from where the linear phase normally ends instead.
=> Downloader: fix forky slices start_block_num after restart.

src/downloader/headers_downloader/downloader_forky.rs, src/downloader/headers_downloader/downloader_tests.rs, src/downloader/headers_downloader/headers/header_slices.rs, src/downloader/headers_downloader/stages/extend_stage.rs, src/downloader/headers_downloader/stages/fork_mode_stage.rs, src/downloader/headers_downloader/stages/mod.rs
In forky phase when the window is full with Saved slices,
we need to slide the window up.
This is done in 2 steps:
1. during execution ExtendStage appends an empty slice to the end.
2. after execution a trim happens at the front of header slices.
It is ok to not cleanup immediately, because we need to exit processing periodically anyway.
=> Downloader: forky - slide full slices.

src/downloader/headers_downloader/downloader.rs, src/downloader/headers_downloader/downloader_forky.rs, src/downloader/headers_downloader/downloader_tests.rs, src/downloader/headers_downloader/stages/fork_mode_stage.rs, src/downloader/headers_downloader/stages/fork_switch_command.rs, src/downloader/headers_downloader/stages/mod.rs, src/downloader/headers_downloader/stages/save_stage.rs, src/downloader/headers_downloader/stages/verify_link_forky_stage.rs, src/downloader/mod.rs, src/stages/downloader.rs
When switch to fork is needed, exit the forky stage loop,
and make an unwind request for the main stage loop.
Process unwind() call by the DB cleanup.
When execution starts again, finalize the switch_to_fork() changes.
Note: in tests there's no unwind, so finalize is called immediately after run
to verify the slices state after unwind.
The stage termination and unwind request is based on the ForkSwitchCommand,
but can be based on some other command.
This can be useful if there's a different situation thata requires unwinding.
=> Downloader: fork unwind.

src/downloader/headers_downloader/downloader.rs, src/downloader/headers_downloader/downloader_tests.rs, src/downloader/headers_downloader/stages/fork_switch_command.rs, src/downloader/headers_downloader/stages/save_stage.rs, src/stages/downloader.rs
CanonicalHeader / LastHeader / HeadersTotalDifficulty tables
need to be updated after switch to fork,
because they were not saved for the fork chain.
This is done as a part of unwind finalize on the next execute iteration.
=> Downloader: update db after switch to fork.

src/downloader/headers_downloader/downloader_forky.rs, src/downloader/headers_downloader/stages/fork_switch_command.rs, src/downloader/headers_downloader/stages/save_stage.rs
Use MutableCursor::append instead of MutableTransaction::set for SaveOrder::Monotonic.
This is supposed to speed up monotonic header slices insertions.
=> Downloader: save headers data with MDBX_APPEND.

src/trie/hash_builder.rs, src/trie/intermediate_hashes.rs, src/trie/node.rs
rewrite the line-by-line C++ port in a more idiomatic way,
get rid off interior mutability workarounds, buffer attributes
and clippy exceptions
=> Rustify the trie module

src/trie/intermediate_hashes.rs
Check if the visited account is absent from HashedStorage and return
EMPTY_ROOT if that is the case. This avoids the state root mismatches
due to wrongly handled SELFDESTRUCTs we have seen.
=> Add a workaround to avoid state root mismatches

src/execution/evm/state.rs, src/lib.rs
Checking if we are within the array bounds is redundant, since each opcode has a constant `required_stack_height` that is checked for before execution.
=> Remove vector range checks from Stack methods

src/p2p/node/node.rs
Right now, downloader(Header and Bodies) stages sometimes can get stuck. I've personally encountered that a few times, log is attached.
This PR seeks to fix that issue.
```bash
2022-05-27T07:15:28.948627Z  INFO P2P node peer info: 42 active (+39 dialing) / 8192 max.
2022-05-27T07:15:33.950020Z  INFO P2P node peer info: 40 active (+39 dialing) / 8192 max.
2022-05-27T07:15:38.950796Z  INFO P2P node peer info: 40 active (+40 dialing) / 8192 max.
2022-05-27T07:15:43.951802Z  INFO P2P node peer info: 39 active (+40 dialing) / 8192 max.
2022-05-27T07:15:48.953066Z  INFO P2P node peer info: 40 active (+42 dialing) / 8192 max.
2022-05-27T07:15:53.954155Z  INFO P2P node peer info: 41 active (+43 dialing) / 8192 max.
2022-05-27T07:15:58.954845Z  INFO P2P node peer info: 41 active (+43 dialing) / …
```
=> feat(sentry): timeout all outbound messages

src/stages/history_index.rs
This PR adds the changes in the genesis block to `AccountHistory`. This is mainly useful because it allows historical state lookups to short circuit (with `None`) when the requested block is prior to the first bit of `AccountHistory`. This trick currently fails for genesis accounts.
=> Add genesis block to AccountHistory

bin/akula-toolbox.rs, bin/akula.rs, src/consensus/beacon.rs, src/consensus/blockchain.rs, src/consensus/mod.rs, src/execution/mod.rs, src/execution/processor.rs, src/rpc/eth.rs, src/rpc/mod.rs, src/rpc/otterscan.rs, src/rpc/trace.rs, src/sentry/devp2p/disc/dns/mod.rs, src/stages/execution.rs
The CL RPC is currently hardcoded to listen on localhost:8551. While it is a good default, and we should keep it, that does not work with docker compose, because each container gets its own IP from internal network, it needs to bind to the container IP.
This PR adds a parameter to CL engine address/port. It is not that good solution, but it works and does minimal changes to other parts of the code. The challenge here is to inject the address/port param into the beacon consensus object, I think a better approach would require a bigger refactoring/cleanup, but I'm not ready for that :)
It only modifies the engine_factory function signature and adds default params to other callers, so it keeps current code semantics while enabling the akula binary to pass the new param.
=> Enable parameterization of CL listen addr/port

Cargo.lock, Cargo.toml, src/sentry/devp2p/disc/v4/node.rs
=> add and use public_ip as fallback

Cargo.lock, bin/akula-rpc.rs, bin/akula.rs, src/accessors/state.rs, src/rpc/debug.rs, src/rpc/mod.rs, src/rpc/trace.rs
Adds gRPC debug API with two new methods for traversing accounts and account storage. Implemented as gRPC stream, with values returned in non-hashed order.
Depends on https://github.com/ledgerwatch/interfaces/pull/127
=> gRPC state traversal

src/accessors/state.rs, src/state/buffer.rs
The account and storage gRPC streams were broken for historical blocks due to a typo (`!=` rather than `==`). This PR fixes that. I've also implemented two optimizations:
1. If the history index shows that the requested block is older than the first write to an account/storage key `None`/`U256::ZERO` can be returned immediately.
2. Since the `walk()` functions are already iterating over the history index they can efficiently identify which block to find changesets in, which is more efficient that calling `read()` which then has to do a history index lookup itself.
=> Optimize historical state access

src/trie/intermediate_hashes.rs
During the trie update, we log an estimate of the remaining time every 30 seconds, for which the elasped time is divided by a progress ratio. For very large updates, like the initial sync of Ethereum mainnet, the measured progress may still be zero when the first message is due. We check for this in order to not divide by zero and panic when computing the Duration.
=> Fix panic in interhashes stage progress message

Cargo.lock, Cargo.toml, bin/akula-toolbox.rs
use `akula-toolbox send-chain-tip --head <hash>` to allow akula download without consensus client
=> add send_chain_tip in toolbox
