.github/workflows/main.yml

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-multiple-events-with-activity-types-or-configuration

avoid double CI on PRs

---

src/accessors/chain.rs
src/models/block.rs

Implement some of the missing database accessors.

Some accessors

---

Cargo.toml
src/stagedsync/stage.rs
src/stages/mod.rs
src/stages/sender_recovery.rs

Naive implementation of stage 4 of the staged sync, recovery of transaction senders. Tbd: concurrency, configurability, unwind method.

Senders recovery stage

---

src/accessors/chain.rs
src/kv/table-defs/db_tables.toml
src/stages/mod.rs
src/stages/tx_lookup.rs

Got some pointers from @Giulio2002.
Please guide me through on what's wrong/missing.
Thanks!

implement tx_lookup stage

---

src/state/delta.rs
src/state/intra_block_state.rs

https://github.com/torquem-ch/silkworm/pull/407

Delta::UpdateBalance

---

src/kv/mdbx.rs
src/kv/remote.rs
src/kv/server.rs
src/kv/traits.rs

https://github.com/ledgerwatch/interfaces/pull/64

Database v4.0

---

src/downloader/headers/fetch_request_stage.rs
src/downloader/sentry_client_reactor.rs

When we send too many header slice fetch request at a time
we start getting SendQueueFull, and pending_count stays positive.
In this case execute() was not awaiting anything, and returning immediately
just to get yet another SendQueueFull leading to a live spin.
Fix this by calling sender.reserve_owned().await.
Note: not using the await fn to avoid holding the sentry.read() lock while awaiting.

FetchRequestStage: avoid log spam on send queue congestion.

---

Cargo.lock
Cargo.toml
bin/akula-ddl.rs
src/downloader/opts.rs

On macOS the database will be inside
~/Library/Application Support/com.akula-bft.akula
On Linux - $HOME/.local/share/akula

Default datadir option using platform-specific paths.

---

src/downloader/sentry_client_reactor.rs

Ensure that SentryClientReactor is Sync.
This makes it possible to be shared across threads.

SentryClientReactor thread-safety.

---

Cargo.toml
src/downloader/downloader_impl.rs
src/downloader/headers/fetch_receive_stage.rs
src/downloader/headers/fetch_request_stage.rs
src/downloader/headers/mod.rs
src/downloader/headers/refill_stage.rs
src/downloader/headers/retry_stage.rs
src/downloader/headers/save_stage.rs
src/downloader/headers/stage.rs
src/downloader/headers/verify_stage.rs
src/downloader/sentry_client_reactor.rs

Add a common protocol implemented by every header downloading stage.

Downloader refactoring: stages trait.

---

src/downloader/headers/downloader.rs
src/downloader/headers/downloader_linear.rs
src/downloader/headers/downloader_preverified.rs
src/downloader/headers/header_slices.rs

Be able to start HeaderSlices from an arbitrary point.
The linear phase starts where the preverified phase ends.

Downloader: HeaderSlices.start_block_num.

---

Cargo.lock
Cargo.toml
src/kv/tables.rs
src/lib.rs
src/stages/interhashes.rs
src/stages/mod.rs

Initial computation of the state root and population of the TrieAccount and TrieStorage tables.

Interhashes stage, part 1

---

.github/workflows/main.yml
.gitignore
src/downloader/headers/downloader_linear.rs
src/downloader/headers/downloader_preverified.rs
src/downloader/headers/mod.rs
src/downloader/headers/verify_stage_linear.rs
src/downloader/headers/verify_stage_preverified.rs

* hardcoded estimated_latest_block_num/trusted_len
* verify linked by parent hash, block nums and timestamps
* stubs for difficulty and PoW

Downloader: linear phase verification stage.

---

src/etl/collector.rs

Tentative fix until we implement a proper solution.

Fix test etl::collector::tests::collect_chunks fails #52

---

src/downloader/headers/downloader.rs
src/downloader/headers/downloader_linear.rs
src/downloader/headers/downloader_preverified.rs
src/downloader/headers/fetch_request_stage.rs
src/downloader/headers/header_slice_verifier.rs
src/downloader/headers/header_slices.rs
src/downloader/headers/mod.rs
src/downloader/headers/save_stage.rs
src/downloader/headers/ui_crossterm.rs
src/downloader/headers/verify_stage_linear.rs
src/downloader/headers/verify_stage_linear_link.rs
src/downloader/headers/verify_stage_preverified.rs

Not only the blocks inside the slice need to be consistent,
but also the first block of a slice must correspond to the last block of a previous slice.
This has to be checked sequentially from the leftmost end.

Downloader: verify slice edges in linear phase.

---

src/models/chainspec.rs
src/models/mod.rs
src/sentry/chain_config.rs
src/sentry/chain_id.rs
src/sentry/mod.rs
src/sentry/sentry_client_impl.rs

Use network_id instead of chain_id.

Downloader: set_status using network_id.

---

src/downloader/headers/downloader.rs
src/downloader/headers/downloader_linear.rs
src/downloader/headers/downloader_preverified.rs
src/downloader/headers/fetch_receive_stage.rs
src/downloader/headers/mod.rs
src/downloader/headers/top_block_estimate_stage.rs
src/sentry/message_decoder.rs
src/sentry/messages.rs

The linear phase needs a top block number to know where to stop.
This block number is estimated based on the incoming NewBlockHashes messages.

Downloader: top block estimation task.

---

src/downloader/headers/downloader_linear.rs
src/downloader/headers/downloader_preverified.rs
src/downloader/headers/ui_crossterm.rs
src/downloader/headers/ui_tracing.rs

It was not possible to distinguish
which phase is running as the log looked the same.

Downloader: log phase name in progress.

---

bin/akula-ddl.rs
src/downloader/downloader_impl.rs
src/downloader/downloader_tests.rs
src/downloader/headers/downloader.rs
src/downloader/headers/downloader_linear.rs
src/downloader/headers/downloader_preverified.rs
src/downloader/headers/save_stage.rs
src/downloader/headers/stage_stream.rs

The downloader will be provided by a single transaction,
and use that in the SaveStage.

Downloader: save using a provided DB transaction.

---

src/downloader/downloader_impl.rs
src/downloader/downloader_tests.rs
src/downloader/headers/downloader.rs
src/downloader/headers/downloader_linear.rs
src/downloader/headers/downloader_preverified.rs
src/downloader/headers/preverified_hashes_config.rs
src/stages/downloader.rs

Start downloading headers from the last known progress point.

Downloader: recover progress.

---

src/downloader/downloader_impl.rs
src/downloader/downloader_tests.rs
src/downloader/headers/downloader.rs
src/downloader/headers/downloader_linear.rs
src/downloader/mod.rs
src/stages/downloader.rs

Remember estimated_top_block_num between stage executions.

Downloader: fix waiting to estimate a top block number.

---

src/downloader/sentry_status_provider.rs

When sentry disconnected, the status stream was pending and didn't return,
because WatchStream is waiting on the watch::changed() future,
but it is not gonna change at this point.
Fix by making this stream eager and always produce a value without awaiting.

Downloader: fix reconnects.

---

bin/consensus-tests.rs

With this change the run time on my MacBook reduces from about 33s to 12s.

Run consensus tests in parallel

---

src/downloader/headers/downloader.rs
src/downloader/headers/downloader_forky.rs
src/downloader/headers/fork_mode_stage.rs
src/downloader/headers/header_slice_verifier.rs
src/downloader/headers/header_slices.rs
src/downloader/headers/mod.rs
src/downloader/headers/save_stage.rs
src/downloader/headers/ui_crossterm.rs
src/downloader/headers/verify_stage_forky_link.rs
src/downloader/headers/verify_stage_linear.rs
src/downloader/headers/verify_stage_linear_link.rs

A new phase for downloading the last 90K headers.
This phase is similar to linear, with a few differences:
* VerifyStageLinearLink is replaced with VerifyStageForkyLink
* VerifyStageForkyLink introduces a "fork mode" (ForkModeStage)
* refill stage is going to be replaced by a different stage

Downloader: forky phase.

---

src/downloader/headers/downloader_forky.rs
src/downloader/headers/downloader_linear.rs
src/downloader/headers/downloader_preverified.rs
src/downloader/headers/downloader_stage_loop.rs
src/downloader/headers/mod.rs

Extrac the logic to DownloaderStageLoop.

Downloader: refactor phase loops.

---

src/downloader/headers/fork_mode_stage.rs
src/downloader/headers/header_slices.rs
src/downloader/headers/ui_crossterm.rs

Implement "happy path" chains extension,
termination conditions, switching to the fork or discarding it.

Downloader: fork mode logic.

---

src/downloader/headers/downloader_forky.rs
src/downloader/headers/fork_mode_stage.rs
src/downloader/headers/header_slices.rs
src/downloader/headers/mod.rs
src/downloader/headers/refetch_stage.rs

The stage is responsible for fetch retries of slices.

Downloader: refetch stage.

---

src/lib.rs
src/trie/hash_builder.rs
src/trie/intermediate_hashes.rs
src/trie/mod.rs
src/trie/node.rs
src/trie/prefix_set.rs
src/trie/util.rs

This is a line-by-line port of silkworm's trie algorithm. There will be follow-ups for the remaining part of the algorithm run against our existing property test, and to refactor/rustify the ported C++ code.

Ported trie algorithm

---

src/downloader/headers_downloader/downloader_tests.rs
src/downloader/headers_downloader/headers/header.rs
src/downloader/headers_downloader/stages/verify_link_forky_stage.rs

Testing fork chain reaching root, or canonical chain reaching top.
Improved:
* do not go to fork mode on the very first block/slice

Downloader: fork mode tests for boundary conditions.

---

src/trie/hash_builder.rs
src/trie/intermediate_hashes.rs

and apply the existing property test to it

Port the rest of silkworm's trie algorithm

---

src/downloader/headers_downloader/stages/save_stage.rs

Saving a precomputed RLP representation is not possible anymore,
because the headers are stored in a different format.

Downloader: SaveStage - remove cached RLP optimization.

---

src/downloader/headers_downloader/downloader.rs
src/downloader/headers_downloader/downloader_forky.rs
src/downloader/headers_downloader/downloader_linear.rs
src/downloader/headers_downloader/stages/save_stage.rs
src/downloader/headers_downloader/stages/verify_link_forky_stage.rs
src/downloader/headers_downloader/stages/verify_link_linear_stage.rs

linear_start_block_id() method was rewinding 1 slice back
to get to a known start_block_hash to pass into VerifyLinkLinearStage.
If instead we pass a trusted parent header of a start_block_num
(aka "trusted anchor"), then there's no need to rewind.
We can assume that start_block_num - 1 is saved in db, so it can be loaded from db.
This saves a full slice re-downloading each time, and simplifies the
start_block_num-related calculations.

Downloader: refactor verify link to use last_verified_header.

---

src/sentry/message_decoder.rs
src/sentry/messages.rs

* decode missing: Status & Transactions
* sort enums

Sentry: decode missing messages.

---

Cargo.lock
bin/akula-rpc.rs
bin/akula.rs
src/consensus/beacon.rs
src/rpc/mod.rs
src/rpc/web3.rs

Add web3_clientVersion

---

bin/akula.rs
src/kv/tables.rs
src/lib.rs
src/state/database_version.rs
src/state/mod.rs

Adds infrastructure for database versioning and migrations.
Hope this makes sense. Solution for #172

Database versioning / migrations

---

Dockerfile

feat: change Docker base image to Fedora

---

bin/akula-rpc.rs
bin/akula.rs

feat: Add Websocket to rpcdaemon

---

src/sentry/devp2p/rlpx.rs

This apparently got yanked during the downloader development.

Fix peer pinger

---

Cargo.lock
bin/akula-rpc.rs
bin/akula-toolbox.rs
bin/akula.rs
src/accessors/state.rs
src/kv/mdbx.rs
src/rpc/mod.rs
src/rpc/parity.rs
src/state/buffer.rs

Less than optimal for historical blocks, but should work nevertheless.
Depends on https://github.com/vorot93/ethereum-jsonrpc/pull/4
Fixes #277

Implement parity_listStorageKeys

---

README.md

Current link is broken. This will fix it.

update website link in readme
